#!/usr/bin/env python3
"""Generate docs/coverage.md from the rule files (rule x ATT&CK x ATLAS x log source x backend).

Usage:
  python scripts/coverage_matrix.py          # write docs/coverage.md
  python scripts/coverage_matrix.py --check  # exit 1 if docs/coverage.md is stale
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tests"))
sys.path.insert(0, str(ROOT / "scripts"))

from esql_harness import known_gaps  # noqa: E402
from harness import SAMPLE_KINDS, load_events, rule_cases  # noqa: E402
from validate_mappings import atlas_techniques, attack_data, validate  # noqa: E402

import yaml  # noqa: E402

OUTPUT = ROOT / "docs" / "coverage.md"
QUERY_FILES = {"Splunk": ("queries/splunk", ".spl"), "ES|QL": ("queries/esql", ".esql")}


def logsource(doc: dict) -> str:
    source = doc.get("logsource", {})
    return " / ".join(str(source[key]) for key in ("product", "service", "category") if key in source)


def render() -> str:
    lines = [
        "# Coverage matrix",
        "",
        "Generated by `make matrix` (`scripts/coverage_matrix.py`) from the rule files. Do not edit by hand.",
        "",
        "Mappings are validated against pinned MITRE ATT&CK v19.2 and MITRE ATLAS 2026.09 (`make mappings`).",
        "Sample counts are events in `tests/data/<rule>/`. Backend cells link to the committed query:",
        "",
        "- **ES|QL: tested** means the committed query runs on Elasticsearch 9.1.5 in CI (`tests/test_esql_execution.py`)",
        "  and matches every positive and no negative or allowlisted sample. **known gap** means a documented",
        "  exception listed in `tests/esql_known_gaps.yml`.",
        "- **Splunk: snapshot only** means the query is generated and snapshot-tested, but not executed on Splunk.",
        "",
        "| Rule | Level | Log source | ATT&CK | ATLAS | Samples (pos / neg / allow) | Splunk | ES\\|QL |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for case in rule_cases():
        docs = [doc for doc in yaml.safe_load_all(case.path.read_text(encoding="utf-8")) if doc]
        main = docs[-1]  # the correlation rule, or the only rule
        source_doc = next(doc for doc in docs if "logsource" in doc)
        mapping = validate(case.path, main)
        attack = [f"{t} {attack_data().techniques[t]['name']}" for t in mapping.techniques]
        if not attack and mapping.tactics:
            attack = [f"tactic: {', '.join(mapping.tactics)}"]
        atlas = [f"{a} {atlas_techniques()[a]['name']}" for a in mapping.atlas]
        counts = " / ".join(str(len(load_events(case.sample(kind)))) for kind in SAMPLE_KINDS)
        rule_link = f"[{main['title']}](../{case.path.relative_to(ROOT).as_posix()})"
        if "correlation" in main:
            rule_link += " (correlation)"
        gaps = known_gaps().get(case.stem, {})
        labels = {"Splunk": "snapshot only", "ES|QL": f"known gap ({', '.join(sorted(gaps))})" if gaps else "tested"}
        backends = []
        for backend, (directory, suffix) in QUERY_FILES.items():
            query = ROOT / directory / f"{case.stem}{suffix}"
            backends.append(f"[{labels[backend]}](../{directory}/{query.name})" if query.exists() else "no")
        lines.append(
            f"| {rule_link} | {main['level']} | {logsource(source_doc)} | {'<br>'.join(attack) or 'none'} "
            f"| {'<br>'.join(atlas)} | {counts} | {' | '.join(backends)} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    content = render()
    if "--check" in argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print("docs/coverage.md is stale: run `make matrix`")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
